spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 690166915653-paa941cs02li19r4b778hldnjbaldp1h.apps.googleusercontent.com
            clientSecret: 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
          github:
            clientId: 482acf418bf96174b896
            clientSecret: c7280ed33c031ab3e8089510c3967cd269b0a2fd
          kakao:
            clientId: 0c96492a94d3847f094fda7ec7a29407
            clientSecret: fyBWI0OmWOAtnW2OrqSCpBAyg2uLFqUC

jwt:
  secret-key: "fasdfasasdflknewqiofdsalkfnqwouie234231412fkdsjafbeuwqpfbdsadflfbasfklwuiqefblskf34214asdkljfbsaldrasdrkljfb"
